name: Build project

on: push

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Rename build files and folder
        if: matrix.targetPlatform == 'StandaloneWindows64'
        run: |
          mv build/StandaloneWindows64/StandaloneWindows64.exe build/StandaloneWindows64/Runebound.exe
          mv build/StandaloneWindows64/StandaloneWindows64_Data build/StandaloneWindows64/Runebound_Data
          mv build/StandaloneWindows64 build/Runebound-Windows64

      - uses: actions/upload-artifact@v4
        with:
          name: Runebound-Windows64
          path: build/Runebound-Windows64
